spring:
  application:
    name: multi-acueductos-api
  datasource:
    url: jdbc:postgresql://localhost:5432/db_acueductos
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: uQ1b9c@#4BvG!8rS2xYpLk7ZtQwEoM5nHfTgVnXz